#pragma once
//https://docs.google.com/document/d/19qzwL-YT_U8nMIzBIrLZtw7b7TNUX8SrNCQFAcU3jeM/edit
//Specific information on nodes and commands here

enum Node {
    DRIVE_AXIS_0 = 0x0,
    DRIVE_AXIS_1 = 0x1,
    DRIVE_AXIS_2 = 0x2,
    DRIVE_AXIS_3 = 0x3,
    DRIVE_AXIS_4 = 0x4,
    DRIVE_AXIS_5 = 0x5,
    RASPBERRY_PI = 0x6,
    CONTROL_TEENSY = 0x7,
    ARM_TEENSY = 0x8,
    GRIPPER_TEENSY = 0x9,
    EA_TEENSY = 0xA
};

enum Command {
    CAN_OPEN_NMT_MESSAGE = 0x0,
    DRIVE_HEARTBEAT_MESSAGE = 0x1,
    DRIVE_EMERGENCY_STOP_MESSAGE = 0x2,
    GET_MOTOR_ERROR = 0x3,
    GET_ENCODER_ERROR = 0x4,
    GET_SENSORLESS_ERROR = 0x5,
    SET_AXIS_NODE_ID = 0x6,
    SET_AXIS_REQUESTED_STATE = 0x7,
    SET_AXIS_STARTUP_CONFIG = 0x8,
    GET_ENCODER_ESTIMATES = 0x9,
    GET_ENCODER_COUNT = 0xA,
    SET_CONTROLLER_MODES = 0xB,
    SET_INPUT_POS = 0xC,
    SET_INPUT_VEL = 0xD,
    SET_INPUT_TORQUE = 0xE,
    SET_LIMITS = 0xF,
    START_ANTICOGGING = 0x10,
    SET_TRAJ_VEL_LIMIT = 0x11,
    SET_TRAJ_ACCEL_LIMIT = 0x12,
    SET_TRAJ_INERTIA = 0x13,
    GET_IQ = 0x14,
    GET_SENSORLESS_ESTIMATES = 0x15,
    REBOOT_DRIVE = 0x16,
    GET_VBUS_VOLTAGE = 0x17,
    CLEAR_ERRORS = 0x18,
    SET_LINEAR_COUNT = 0x19,
    SET_POSITION_GAIN = 0x1A,
    SET_VEL_GAINS = 0x1B,
    CAN_OPEN_HEARTBEAT_MESSAGE = 0x700,
    CURRENT_SENSOR_READINGS = 0x1C,
    VOLTAGE_SENSOR_READINGS = 0x1D,
    GYROSCOPE_SENSOR_READINGS = 0x1E
};